---
# Playbook to delete a routing instance in an SRX firewall
# Variable are pulled from a file
#

- name: Ansible generic configs
  vars_files:
    - ~/.vars-aci-credentials.yml
    - "{{ varfile }}"

  hosts: "{{ general.fw }}"

  connection: local
  gather_facts: no

  vars:
    playbook_version: '2.2'
    deploy_config: "n"

    gv_general: "{{ gv_general_default|combine(override_gv_general) }}"
    gv_aci: "{{ gv_aci_default|combine(override_gv_aci) }}"
    gv_srx: "{{ gv_srx_default|combine(override_gv_srx) }}"

  tasks:
  #
  # Compare playbook_version and input_vars_version
  #
  - name: 'Check input_vars_version' 
    fail: msg="playbook_version and input_vars_version do not match. Maybe you used the wrong template file?"
    when: playbook_version != input_vars_version

  #
  # Get timestamp to be used to create unique filenames
  #
  - name: Get timestamp as string
    command: "date +%Y%m%d-%H%M"
    register: ts_file

  #
  # Prepare SRX config file
  #
  - name: Prepare SRX config file
    template:
      src: jinja-templates/srx/srx-vr-delete.j2
      dest: ../data/output-files/srx-vr-delete-{{general.fw}}-{{gv_srx.ri_prefix+srx.ri_id}}-{{ ts_file.stdout }}.txt
    # no_log: true

  #
  # Create configuration diff using Napalm
  #
  - name: Create configuration diff using Napalm
    napalm_install_config:
      hostname: "{{ ansible_host }}"
      username: "{{ apic_user }}"
      password: "{{ apic_pass }}"
      dev_os: "junos"
      config_file: "../data/output-files/srx-vr-delete-{{general.fw}}-{{gv_srx.ri_prefix+srx.ri_id}}-{{ ts_file.stdout }}.txt"
      commit_changes: False
      replace_config: False
      optional_args: { 'ignore_warning': True }
      get_diffs: True
      diff_file: "../data/output-files/srx-vr-delete-{{general.fw}}-{{gv_srx.ri_prefix+srx.ri_id}}-diff-{{ ts_file.stdout }}.txt"
    register: result

  #
  # Print config diff
  #
  - name: Print config diff
    debug: 
      msg={{ result.msg.split('\n') }}

  #
  # Ask user to commit this config
  #
  - name: Ask user to commit this config
    pause:
      prompt: "Do you want to commit this config? (y/N)"
    register: deploy_config

  #
  # Change configuration using Napalm
  #
  - name: Change configuration using Napalm
    napalm_install_config:
      hostname: "{{ ansible_host }}"
      username: "{{ apic_user }}"
      password: "{{ apic_pass }}"
      dev_os: "junos"
      config_file: "../data/output-files/srx-vr-delete-{{general.fw}}-{{gv_srx.ri_prefix+srx.ri_id}}-{{ ts_file.stdout }}.txt"
      commit_changes: True
      replace_config: False
      optional_args: { 'ignore_warning': True }
      get_diffs: True
      diff_file: "../data/output-files/srx-vr-delete-{{general.fw}}-{{gv_srx.ri_prefix+srx.ri_id}}-diff-{{ ts_file.stdout }}.txt"
    register: result

# This is the end, my friend
...
